
OPENOCD_HOME ?= /PATH/TO/YOUR_OPENOCD_INSTALL

# supported middleware : ESP8266_AT_parser, Linux
MIDDLEWARE ?= Linux

# supported platform : STM32F4 (currently STM32F446 Nucleo board, ARM-v7M CPU), 
#                      RaspBerry PI 3B+ (ARM-v8A CPU)
PLATFORM ?= unknown

